# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Capture Screen"
  lane :capture_screen do
    gradle(task: "clean assembleDebug assembleAndroidTest")
    screengrab
    sh "../utils.sh copy_screenshots"
  end

  desc "Upload Strings to Crowdin"
  lane :upload_strings do
    #sh "cd ..;./utils.sh title.strings toxml"
    #sh "cd ..;./utils.sh keywords.strings toxml"
    sh "cd ..;crowdin upload sources"
  end

  desc "Download Strings from Crowdin"
  lane :download_strings do
    sh "cd ..;crowdin download"
    #sh "cd ..;./utils.sh 0 fromxml"
  end

  desc "Add Frames to Screenshots"
  lane :add_frames do
    frameit(
      use_platform:"ANDROID",
      path: "./fastlane/",
      force_device_type: "Google Pixel 4"
    )
  end

    desc "Submit a new Beta Build to Crashlytics Beta"
    lane :release do
      gradle(
        task: "bundle",
        build_type: "Release"
      )
    end

    desc "Deploy a new version to the Google Play"
    lane :deploy do
      sh "../utils.sh delete_raw"
      upload_to_play_store(
      track: "production",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      "skip_upload_aab": false,
      "skip_upload_metadata": true,
      "skip_upload_changelogs": true
      )
    end

end
